[package]
name = "cognate"
version = "0.1.1"
edition = "2024"

[dependencies]
iced = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pulldown-cmark = "0.10"
native-dialog = "0.6"
toml = "0.8"
